---
# Emile Schons - 04.05.2021
# This playbook can be run with ansible-playbook Provision_PopOS_localhost.yml --ask-become-pass -u mulles
# This playbook is designed to correct the following error when flashing STM32 with plattformio (PIO):
# Error: libusb_open() failed with LIBUSB_ERROR_ACCESS
# Error: open failed


- name: "Configure Host System with is PopOS on Lemur pro (lemp7) from System76"
  hosts: localhost
  connection: local 
    
  tasks:


# Configure OPENOCD for Linux Host 
  # lsusb gives the device we are using: ATTRS{idVendor}=="0483", ATTRS{idProduct}=="374b
  # based on https://stackoverflow.com/questions/41066653/openocd-error-libusb-open-failed-with-libusb-error-not-supported
  # and https://github.com/bcmi-labs/OpenOCD/blob/master/contrib/99-openocd.rules
  # and https://github.com/bcmi-labs/OpenOCD (Readme)
  
    - name: Copy this file 99-openocd.rules to /etc/udev/rules.d/
      copy:
        content: |
              # Copy this file to /etc/udev/rules.d/

              ACTION!="add|change", GOTO="openocd_rules_end"
              SUBSYSTEM!="usb|tty|hidraw", GOTO="openocd_rules_end"

              # Please keep this list sorted by VID:PID

              # opendous and estick
              ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="204f", MODE="664", GROUP="plugdev"

              # Original FT232/FT245 VID:PID
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", MODE="664", GROUP="plugdev"

              # Original FT2232 VID:PID
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6010", MODE="664", GROUP="plugdev"

              # Original FT4232 VID:PID
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6011", MODE="664", GROUP="plugdev"

              # Original FT232H VID:PID
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6014", MODE="664", GROUP="plugdev"

              # DISTORTEC JTAG-lock-pick Tiny 2
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="8220", MODE="664", GROUP="plugdev"

              # TUMPA, TUMPA Lite
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="8a98", MODE="664", GROUP="plugdev"
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="8a99", MODE="664", GROUP="plugdev"

              # XDS100v2
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="a6d0", MODE="664", GROUP="plugdev"

              # Xverve Signalyzer Tool (DT-USB-ST), Signalyzer LITE (DT-USB-SLITE)
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="bca0", MODE="664", GROUP="plugdev"
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="bca1", MODE="664", GROUP="plugdev"

              # TI/Luminary Stellaris Evaluation Board FTDI (several)
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="bcd9", MODE="664", GROUP="plugdev"

              # TI/Luminary Stellaris In-Circuit Debug Interface FTDI (ICDI) Board
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="bcda", MODE="664", GROUP="plugdev"

              # egnite Turtelizer 2
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="bdc8", MODE="664", GROUP="plugdev"

              # Section5 ICEbear
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="c140", MODE="664", GROUP="plugdev"
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="c141", MODE="664", GROUP="plugdev"

              # Amontec JTAGkey and JTAGkey-tiny
              ATTRS{idVendor}=="0403", ATTRS{idProduct}=="cff8", MODE="664", GROUP="plugdev"

              # STLink v1
              ATTRS{idVendor}=="0483", ATTRS{idProduct}=="3744", MODE="664", GROUP="plugdev"

              # STLink v2
              ATTRS{idVendor}=="0483", ATTRS{idProduct}=="3748", MODE="664", GROUP="plugdev"

              # STLink v2-1
              ATTRS{idVendor}=="0483", ATTRS{idProduct}=="374b", MODE="664", GROUP="plugdev"

              # Hilscher NXHX Boards
              ATTRS{idVendor}=="0640", ATTRS{idProduct}=="0028", MODE="664", GROUP="plugdev"

              # Hitex STR9-comStick
              ATTRS{idVendor}=="0640", ATTRS{idProduct}=="002c", MODE="664", GROUP="plugdev"

              # Hitex STM32-PerformanceStick
              ATTRS{idVendor}=="0640", ATTRS{idProduct}=="002d", MODE="664", GROUP="plugdev"

              # Amontec JTAGkey-HiSpeed
              ATTRS{idVendor}=="0fbb", ATTRS{idProduct}=="1000", MODE="664", GROUP="plugdev"

              # IAR J-Link USB
              ATTRS{idVendor}=="1366", ATTRS{idProduct}=="0101", MODE="664", GROUP="plugdev"
              ATTRS{idVendor}=="1366", ATTRS{idProduct}=="0102", MODE="664", GROUP="plugdev"
              ATTRS{idVendor}=="1366", ATTRS{idProduct}=="0103", MODE="664", GROUP="plugdev"
              ATTRS{idVendor}=="1366", ATTRS{idProduct}=="0104", MODE="664", GROUP="plugdev"

              # J-Link-OB (onboard)
              ATTRS{idVendor}=="1366", ATTRS{idProduct}=="0105", MODE="664", GROUP="plugdev"

              # Raisonance RLink
              ATTRS{idVendor}=="138e", ATTRS{idProduct}=="9000", MODE="664", GROUP="plugdev"

              # Debug Board for Neo1973
              ATTRS{idVendor}=="1457", ATTRS{idProduct}=="5118", MODE="664", GROUP="plugdev"

              # Olimex ARM-USB-OCD
              ATTRS{idVendor}=="15ba", ATTRS{idProduct}=="0003", MODE="664", GROUP="plugdev"

              # Olimex ARM-USB-OCD-TINY
              ATTRS{idVendor}=="15ba", ATTRS{idProduct}=="0004", MODE="664", GROUP="plugdev"

              # Olimex ARM-JTAG-EW
              ATTRS{idVendor}=="15ba", ATTRS{idProduct}=="001e", MODE="664", GROUP="plugdev"

              # Olimex ARM-USB-OCD-TINY-H
              ATTRS{idVendor}=="15ba", ATTRS{idProduct}=="002a", MODE="664", GROUP="plugdev"

              # Olimex ARM-USB-OCD-H
              ATTRS{idVendor}=="15ba", ATTRS{idProduct}=="002b", MODE="664", GROUP="plugdev"

              # USBprog with OpenOCD firmware
              ATTRS{idVendor}=="1781", ATTRS{idProduct}=="0c63", MODE="664", GROUP="plugdev"

              # TI/Luminary Stellaris In-Circuit Debug Interface (ICDI) Board
              ATTRS{idVendor}=="1cbe", ATTRS{idProduct}=="00fd", MODE="664", GROUP="plugdev"

              # Marvell Sheevaplug
              ATTRS{idVendor}=="9e88", ATTRS{idProduct}=="9e8f", MODE="664", GROUP="plugdev"

              # CMSIS-DAP compatible adapters
              ATTRS{product}=="*CMSIS-DAP*", MODE="664", GROUP="plugdev"

              LABEL="openocd_rules_end"
        dest: /etc/udev/rules.d/99-openocd.rules
      become: yes # sudo in order to add udev files
    
    
    - name: Ensure group "plugdev" exists, else it creat the group sudo usermod -a -G plugdev pi
      ansible.builtin.group:
        name: plugdev
        state: present  
        
    - name: Add group plugdev to the user 'mulles'
      ansible.builtin.user:
        name: mulles
        groups: plugdev
        append: yes
      become: yes #  sudo 
      
    - name: In order to not reboot the system 
      shell: udevadm control --reload
      register: output
    - debug: var=output.stdout_lines 
      become: yes #  sudo         

  
    
# PopOS setup done.     
        
    
    - name: Tell user to unplug and replug  ST-Link device.
      debug:
        msg: Do not forget to Unplug and replug the Serial to USB Device aka Programmer now. Setup is done. If it does not work please reboot your machine
        
        
        
        
        
        
